/* Generated By:JavaCC: Do not edit this line. P6EJ1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface P6EJ1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int DECIMAL = 5;
  /** RegularExpression Id. */
  int BINARIO = 6;
  /** RegularExpression Id. */
  int OCTAL = 7;
  /** RegularExpression Id. */
  int MAYOR = 8;
  /** RegularExpression Id. */
  int MENOR = 9;
  /** RegularExpression Id. */
  int IGUAL = 10;
  /** RegularExpression Id. */
  int MAYOIG = 11;
  /** RegularExpression Id. */
  int MENOIG = 12;
  /** RegularExpression Id. */
  int DISTINTO = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELIF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int X = 18;
  /** RegularExpression Id. */
  int RAIZ = 19;
  /** RegularExpression Id. */
  int SOLVE = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int ANS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\" \"",
    "\"\\n\"",
    "\";\"",
    "<DECIMAL>",
    "<BINARIO>",
    "<OCTAL>",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "<IF>",
    "<ELIF>",
    "<THEN>",
    "<ELSE>",
    "<X>",
    "\"RT\"",
    "\"SV\"",
    "<ID>",
    "\"$\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
  };

}
